### ISSUE TITLE
Winform on Linux problems searching LibX11

### ISSUE THREAD

**Issue by fanoI** [yzrmn/System.CoreFX.Forms#1]
Tried to launch a very simple Winform application (only an empty form really) on Red Hat Enterprise Linux but it SEGFAULT:

> Unhandled Exception: System.TypeInitializationException: The type initializer for 'System.Windows.Forms.XplatUI' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'libX11': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at System.Windows.Forms.XplatUIX11.XInitThreads()
   at System.Windows.Forms.XplatUIX11..ctor() in C:\Users\fano\Documents\GitHub\WinForms CoreRT\src\System\Windows\Forms\XplatUIX11.cs:line 257
   at System.Windows.Forms.XplatUIX11.GetInstance() in C:\Users\fano\Documents\GitHub\WinForms CoreRT\src\System\Windows\Forms\XplatUIX11.cs:line 291
   at System.Windows.Forms.XplatUI..cctor() in C:\Users\fano\Documents\GitHub\WinForms CoreRT\src\System\Windows\Forms\XplatUI.cs:line 112
   --- End of inner exception stack trace ---
   at System.Windows.Forms.XplatUI.EnableThemes() in C:\Users\fano\Documents\GitHub\WinForms CoreRT\src\System\Windows\Forms\XplatUI.cs:line 644
   at System.Windows.Forms.Application.EnableVisualStyles() in C:\Users\fano\Documents\GitHub\WinForms CoreRT\src\System\Windows\Forms\Application.cs:line 489
   at TestCoreFXWinForms.Program.Main(String[] args) in C:\Users\fano\Documents\Visual Studio 2017\Projects\TestCoreFXWinForms\TestCoreFXWinForms\Program.cs:line 11
Aborted (core dumped)

**Comment by fanoI** [comment]
Applying 2 now I have this other exception that I sincerely neither understand what it means:

>Unhandled Exception: System.TypeInitializationException: The type initializer for 'System.Windows.Forms.WindowsFormsSynchronizationContext' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Windows.Forms.XplatUI' threw an exception. ---> System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "keyboards.resources" was correctly embedded or linked into assembly "System.CoreFX.Forms" at compile time, or that all the satellite assemblies required are loadable and fully signed.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at System.Windows.Forms.KeyboardLayouts.LoadLayouts()
   at System.Windows.Forms.KeyboardLayouts.get_Layouts()
   at System.Windows.Forms.X11Keyboard.DetectLayout(KeyboardLayouts layouts)
   at System.Windows.Forms.X11Keyboard.EnsureLayoutInitialized()
   at System.Windows.Forms.X11Keyboard..ctor(IntPtr display, IntPtr clientWindow)
   at System.Windows.Forms.XplatUIX11.SetDisplay(IntPtr display_handle)
   at System.Windows.Forms.XplatUIX11..ctor()
   at System.Windows.Forms.XplatUIX11.GetInstance()
   at System.Windows.Forms.XplatUI..cctor()
   --- End of inner exception stack trace ---
   at System.Windows.Forms.XplatUI.get_MenuAccessKeysUnderlined()
   at System.Windows.Forms.Theme.get_MenuAccessKeysUnderlined()
   at System.Windows.Forms.SystemInformation.get_MenuAccessKeysUnderlined()
   at System.Windows.Forms.Control..ctor()
   at System.Windows.Forms.WindowsFormsSynchronizationContext..cctor()
   --- End of inner exception stack trace ---
   at System.Windows.Forms.WindowsFormsSynchronizationContext.get_AutoInstall()
   at System.Windows.Forms.Control..ctor()
   at System.Windows.Forms.ScrollableControl..ctor()
   at System.Windows.Forms.ContainerControl..ctor()
   at System.Windows.Forms.Form..ctor()
   at TestCoreFXWinForms.Form1..ctor()
   at TestCoreFXWinForms.Program.Main(String[] args)
Aborted (core dumped)

If culture == Linux locale I've really anything particular set:

>[fano@menarello publish]$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Comment by yzrmn** [comment]
Hey, I just saw this (didn't get any notification). I will have a detailed look at this later today and maybe we can figure it out :) Do you have Gitter?
